config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :mentors

  resources :students

end

app/models/mentor.rb
class Mentor < ActiveRecord::Base

  # Ensure the mentor has a name
  validates :name, presence: true

  # Ensure the mentor has some skills to offer
  validates :skills, presence: true

  # Ensure the mentor has an email
  validates :email, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base

  # Ensure the student has a name
  validates :name, presence: true

  # Ensure the student wants some skills
  validates :wanted_skills, presence: true

  # Ensure the student has an email
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  # New Mentor
  def new
    @mentor = Mentor.new
  end

  # Edit an Existing Mentor
  def edit
    @mentor = Mentor.find(params[:id])
  end

  # Create a new mentor
  def create
    @mentor = Mentor.new(mentor_params)

    # If the mentor isn't valid, get outta there
    if @mentor.save
      redirect_to @mentor
    else
      render 'new'
    end
  end

  # Show specific mentor
  def show
    @mentor = Mentor.find(params[:id])
  end

  # Show all Mentors
  def index
    @mentors = Mentor.all
  end

  # Update an mentor
  def update
    @mentor = Mentor.find(params[:id])

    if @mentor.update(mentor_params)
      redirect_to @mentor
    else
      render 'edit'
    end
  end

  # Destroy Things
  def destroy
    @mentor = Mentor.find(params[:id])
    @mentor.destroy

    redirect_to mentors_path
  end

  # Private Methods
  private

  def mentor_params
    params.require(:mentor).permit(:name,:skills,:email,:twitter)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # New Student
  def new
    @student = Student.new
  end

  # Edit Existing Student
  def edit
    @student = Student.find(params[:id])
  end

  # Create a new student
  def create
    @student = Student.new(student_params)

    # If the student isn't valid, get outta there
    if @student.save
      redirect_to @student
    else
      render 'new'
    end
  end

  # Show specific Student
  def show
    @student = Student.find(params[:id])
  end

  # Show all students
  def index
    @students = Student.all
  end

  # Update an record
  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to @student
    else
      render 'edit'
    end
  end

  # Destroy things
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    redirect_to students_path
  end

  # Private Methods
  private

  def student_params
    params.require(:student).permit(:name,:wanted_skills,:email,:twitter)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PearupsClub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mentors/_form.html.erb
<%= form_for @mentor  do |f| %>

  <% if @mentor.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@mentor.errors.count, "error") %> prohibited
        this mentor from being saved:
      </h2>
      <ul>
        <% @mentor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :skills %><br>
    <%= f.text_area :skills %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  <p>

  <p>
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/mentors/edit.html.erb
<h1>Edit an Mentor</h1>

<%= render 'form' %>

<%= link_to 'Back', mentors_path %>

app/views/mentors/index.html.erb
<h1>Pearups Mentors</h1>

<table>
  <tr>
    <th>Mentor Name</th>
    <th>Skills</th>
    <th>Email</th>
    <th>Twitter</th>
    <th colspan="3"></th>
  </tr>

  <% @mentors.each do |mentor| %>
    <tr>
      <td><%= mentor.name %></td>
      <td><%= mentor.skills %></td>
      <td><%= mentor.email %></td>
      <td><%= mentor.twitter %></td>
      <td><%= link_to 'Profile', mentor_path(mentor) %></td>
      <td><%= link_to 'Edit', edit_mentor_path(mentor) %></td>
      <td><%= link_to 'Delete', mentor_path(mentor),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Become a Mentor!', new_mentor_path %> |
<%= link_to 'Back', welcome_index_path %>

app/views/mentors/new.html.erb
<h1>Become an Mentor!</h1>

<%= render 'form' %>

<%= link_to 'Back', mentors_path %>

app/views/mentors/show.html.erb
<p>
  <strong>Mentor:</strong>
  <%= @mentor.name %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @mentor.skills %>
</p>

<p>
  <strong>Email:</strong>
  <%= @mentor.email %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @mentor.twitter %>
</p>

<%= link_to 'Back', mentors_path %> |
<%= link_to 'Edit', edit_mentor_path(@mentor) %>

app/views/students/_form.html.erb
<%= form_for @student  do |f| %>

  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@student.errors.count, "error") %> prohibited
        this student from being saved:
      </h2>
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :wanted_skills %><br>
    <%= f.text_area :wanted_skills %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  <p>

  <p>
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/students/edit.html.erb
<h1>Edit an Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>All Students</h1>

<table>
  <tr>
    <th>Student Name</th>
    <th>Skills Desired</th>
    <th>Email</th>
    <th>Twitter</th>
    <th colspan="3"></th>
  </tr>

  <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.wanted_skills %></td>
      <td><%= student.email %></td>
      <td><%= student.twitter %></td>
      <td><%= link_to 'Profile', student_path(student) %></td>
      <td><%= link_to 'Edit', edit_student_path(student) %></td>
      <td><%= link_to 'Delete', student_path(student),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Become a Student!', new_student_path %> |
<%= link_to 'Back', welcome_index_path %></br>

app/views/students/new.html.erb
<h1>Become an Student!</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p>
  <strong>Student:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Desired Skills:</strong>
  <%= @student.wanted_skills %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @student.twitter %>
</p>

<%= link_to 'Back', students_path %> |
<%= link_to 'Edit', edit_student_path(@student) %>

app/views/welcome/index.html.erb
<h1>Welcome to Pearups!</h1>

<p>
  <%= link_to 'Browse Mentors', controller: 'mentors' %>
  <%= link_to 'Become an Mentor!', new_mentor_path %>
</p>

<p>
  <%= link_to 'Browse Students', controller: 'students' %>
  <%= link_to 'Become an Student!', new_student_path %>
</p>